# Este flujo de trabajo automatiza el backup diario del proyecto GC-2 en Supabase.
name: Supabase Daily Backup GC-2

# Se ejecuta todos los días a las 23:59 (hora UTC) y se puede activar manualmente.
on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

# Permisos para el repositorio.
permissions:
  contents: read

jobs:
  gc2_backup_job:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Descargar el backup de la base de datos de GC-2 usando un contenedor Docker para forzar IPv4
      - name: Dump GC-2 database with Docker
        run: |
          # Usamos un contenedor de Docker con el cliente de postgresql preinstalado.
          # Esto nos da un entorno de red controlado y confiable.
          # El flag --network host fuerza a Docker a usar la red del host, que se comporta mejor.
          docker run --rm --network host -e PGHOST="db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co" \
            -e PGUSER="postgres" \
            -e PGPASSWORD="${{ secrets.SUPABASE_DB_PASSWORD }}" \
            -e PGDATABASE="postgres" \
            -v "$PWD":/backups \
            public.ecr.aws/supabase/postgres:15.1.0.54-rc0 \
            pg_dump --data-only -f /backups/gc2-backup-$(date +'%Y-%m-%d').sql
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Configurar la clave SSH para Hostinger
      - name: Setup SSH key for Hostinger
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      # Transferir el backup y limpiar archivos viejos en Hostinger
      - name: Transfer and cleanup GC-2 backups on Hostinger
        run: |
          BACKUP_FILE=gc2-backup-$(date +'%Y-%m-%d').sql
          rsync -avz \
            -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
            $BACKUP_FILE \
            ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_HOST }}:/home/${{ secrets.HOSTINGER_SSH_USER }}/public_html/Backups/

          ssh -p 65002 -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd /home/${{ secrets.HOSTINGER_SSH_USER }}/public_html/Backups/
            # Eliminar solo los backups de GC-2 de mas de 7 dias
            find . -name "gc2-backup-*.sql" -mtime +7 -delete
            echo "Limpieza de backups de GC-2 completada."
          EOF
