# Este flujo de trabajo automatiza el backup diario del proyecto GC-2 en Supabase.
name: Supabase Daily Backup GC-2

# Se ejecuta todos los días a las 23:59 (hora UTC) y se puede activar manualmente.
on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

# Permisos para el repositorio.
permissions:
  contents: read

jobs:
  gc2_backup_job:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Encontrar la dirección IPv4 del servidor de Supabase y guardarla como una variable de entorno.
      - name: Find Supabase IPv4 address
        id: get_ipv4
        run: |
          # El comando 'host' busca la dirección A (IPv4) del host de Supabase.
          # La opción '-T' deshabilita la resolución IPv6 temporalmente para este paso.
          # Usamos 'awk' para extraer solo la dirección IP de la respuesta.
          ipv4=$(host -T a db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co | awk '/has address/ { print $4 }')
          echo "SUPABASE_IPV4=$ipv4" >> $GITHUB_ENV
        shell: bash

      # Descargar el backup de la base de datos de GC-2 usando una acción de GitHub.
      - name: Dump GC-2 database
        uses: tj-actions/pg-dump@v3
        with:
          # Usamos la dirección IPv4 que encontramos en el paso anterior.
          # Esto garantiza que el runner no intente usar IPv6.
          database_url: "postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD }}@${{ env.SUPABASE_IPV4 }}:5432/postgres"
          path: "gc2-backup-$(date +'%Y-%m-%d').sql"
          options: "-Fc --data-only"

      # Configurar la clave SSH para Hostinger
      - name: Setup SSH key for Hostinger
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      # Transferir el backup y limpiar archivos viejos en Hostinger
      - name: Transfer and cleanup GC-2 backups on Hostinger
        run: |
          BACKUP_FILE=gc2-backup-$(date +'%Y-%m-%d').sql
          rsync -avz \
            -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
            $BACKUP_FILE \
            ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_HOST }}:/home/${{ secrets.HOSTINGER_SSH_USER }}/public_html/Backups/

          ssh -p 65002 -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd /home/${{ secrets.HOSTINGER_SSH_USER }}/public_html/Backups/
            # Eliminar solo los backups de GC-2 de mas de 7 dias
            find . -name "gc2-backup-*.sql" -mtime +7 -delete
            echo "Limpieza de backups de GC-2 completada."
          EOF
